### ISSUE TITLE
Request to add 'ROT13' cipher method.

### ISSUE THREAD

**Issue by Viswalahiri** [AjitZero/Scram-CLI#2]
@AjitZero 

I'd like to add a new cipher method "ROT13" to the list of cipher algorithms. 

Here's a Wikipedia link addressing the following algorithm [ROT13](https://en.wikipedia.org/wiki/ROT13)

Here is a link [ROT 13 Dynamic Implementation](https://rot13.com/) that you can look at.

**Comment by ajitzero** [comment]
ROT13 seems to be a special case of Caesar Cipher, which I have already implemented. If you pass `13` as the input for Caeser Cipher, you can easily replace the need for ROT13.

Try looking up other encoding algorithms.

**Comment by Viswalahiri** [comment]
@AjitZero 

Nice observation with the 'ROT13'.

I feel like a [Book Cipher](https://kifanga.com/what-is-book-cipher/) would be a nice addition to the already existing list of ciphers.

To implement the encoding logic, one would have to take the string that is to be encoded and an appropriate sentence or verse. (Ideally from a book)

**Comment by ajitzero** [comment]
How do you intend to implement it?

**Comment by ajitzero** [comment]
This won't added to the project as of now.
